apiVersion: v1
kind: ConfigMap
metadata:
  name: dbsettings
  namespace: emsapp

data:
    # Common Settings
        DRIVERCLASSNAME: com.mysql.jdbc.Driver
        DIALECT: org.hibernate.dialect.MySQLDialect
        DATABASEURL: jdbc:mysql://172.27.59.51:3306/test
