apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ems-deploy
  namespace: emsapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: emsapp
    spec:
        containers:
        - name: emsapp
          image: avish1990/ems:5bc24f875e951106ced3e29f98bb532b2c58b19e-1.20
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c" ]
          args: [ "bin/catalina.sh start && tail -f /dev/null" ]
          env:
           - name: DATABASEURL
             valueFrom:
               configMapKeyRef:
                       name: dbsettings
                       key: DATABASEURL
           - name: DBUSERNAME
             valueFrom:
               secretKeyRef:
                       name: dbsecret
                       key: DBUSERNAME
           - name: DBPASSWORD
             valueFrom:
               secretKeyRef:
                       name: dbsecret
                       key: DBPASSWORD
           - name: DIALECT
             valueFrom:
               configMapKeyRef:
                       name: dbsettings
                       key: DIALECT
           - name: DRIVERCLASSNAME
             valueFrom:
               configMapKeyRef:
                       name: dbsettings
                       key: DRIVERCLASSNAME
          ports:
          - name: http
            containerPort: 9020
