apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ems-deploy
  namespace: emsapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2        # how many pods we can add at a time
      maxUnavailable: 0  # maxUnavailable define how many pods can be unavailable
                         # during the rolling update
  template:
    metadata:
      labels:
        app: emsapp
    spec:
        containers:
        - name: emsapp
          image: avish1990/ems:c567968765b23a14f3a1fed4d916f549a7da8c7e-1.26
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c" ]
          args: [ "bin/catalina.sh start && tail -f /dev/null" ]
          env:
           - name: DATABASEURL
             valueFrom:
               configMapKeyRef:
                       name: dbsettings
                       key: DATABASEURL
           - name: DBUSERNAME
             valueFrom:
               secretKeyRef:
                       name: dbsecret
                       key: DBUSERNAME
           - name: DBPASSWORD
             valueFrom:
               secretKeyRef:
                       name: dbsecret
                       key: DBPASSWORD
           - name: DIALECT
             valueFrom:
               configMapKeyRef:
                       name: dbsettings
                       key: DIALECT
           - name: DRIVERCLASSNAME
             valueFrom:
               configMapKeyRef:
                       name: dbsettings
                       key: DRIVERCLASSNAME
          ports:
          - name: http
            containerPort: 9020
